/* Generated by :claw at 2026-02-08T17:59:32.971906Z */

#if defined(__cplusplus)
#include <new>
#endif

#define SDL_MAIN_HANDLED 1

#include "SDL3/SDL.h"
#include "SDL3/SDL_platform.h"
#include "SDL3/SDL_vulkan.h"
#include "SDL3/SDL_opengl.h"
#include "src/lib/SDL_build_config.x86_64-pc-linux-gnu.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API struct SDL_GUID* __claw_SDL_StringToGUID(struct SDL_GUID* __claw_result_, const char* pchGUID) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_guid.h:98:38
(*__claw_result_) = SDL_StringToGUID(pchGUID);
return __claw_result_;
}

__CLAW_API void __claw_SDL_SetGPUBlendConstants(SDL_GPURenderPass* render_pass, struct SDL_FColor* blend_constants) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_gpu.h:3340:34
SDL_SetGPUBlendConstants(render_pass, *blend_constants);
}

__CLAW_API void __claw_SDL_GetJoystickGUIDInfo(struct SDL_GUID* guid, Uint16* vendor, Uint16* product, Uint16* version, Uint16* crc16) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_joystick.h:987:34
SDL_GetJoystickGUIDInfo(*guid, vendor, product, version, crc16);
}

__CLAW_API struct SDL_GUID* __claw_SDL_GetJoystickGUIDForID(struct SDL_GUID* __claw_result_, SDL_JoystickID instance_id) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_joystick.h:316:38
(*__claw_result_) = SDL_GetJoystickGUIDForID(instance_id);
return __claw_result_;
}

__CLAW_API struct SDL_GUID* __claw_SDL_GetJoystickGUID(struct SDL_GUID* __claw_result_, SDL_Joystick* joystick) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_joystick.h:874:38
(*__claw_result_) = SDL_GetJoystickGUID(joystick);
return __claw_result_;
}

__CLAW_API char* __claw_SDL_GetGamepadMappingForGUID(struct SDL_GUID* guid) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_gamepad.h:467:36
return (char*) SDL_GetGamepadMappingForGUID(*guid);
}

__CLAW_API struct SDL_GUID* __claw_SDL_GetGamepadGUIDForID(struct SDL_GUID* __claw_result_, SDL_JoystickID instance_id) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_gamepad.h:626:38
(*__claw_result_) = SDL_GetGamepadGUIDForID(instance_id);
return __claw_result_;
}

__CLAW_API void __claw_SDL_GUIDToString(struct SDL_GUID* guid, char* pszGUID, int cbGUID) {
// /home/jboehland/work/render-stack-meta/repos/render-stack-sdl3-ffi/src/lib/sdl/include/SDL3/SDL_guid.h:80:34
SDL_GUIDToString(*guid, pszGUID, cbGUID);
}

#if defined(__cplusplus)
}
#endif
